# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pyGN_bHN8oVGMzYHqcDKsnzI-Khq_XB1

Numpy
"""

import numpy as np

a=np.array([1,2,3,4])
b=np.array([2,3,4,5])

a*b

type(a)

np.zeros(10)

np.zeros(5,dtype=int)

np.ones((3,5),dtype=int)

np.full((3,5),3)

np.arange(0,31,3)

np.linspace(0,1,10)

np.random.randint(0,10,(3,3))

np.random.normal(10,4,(3,4))

