# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UaLDPotBkk0cPbo5R1UtO7moZs55KvnW
"""

import pandas as pd

seri=pd.Series([1,2,3,4,5])

seri.head(3)

a=pd.Series([23,45,67,12,76,14,6],index=[1,3,5,7,9,11,13])

pd.concat([a,a])

import numpy as np
a=np.array([1,3,444,67,998])
seri=pd.Series(a)
seri

seri[0:3]

seri[4]

seri1=pd.Series([121,300,444,67],
                index=["ref","loj","cart","rf"])

seri1

seri1.index

list(seri1.items())

seri1.values

"ref" in seri1

seri1["ref"]

l=[1,2,39,67,90]
l

pd.DataFrame(l,columns=["degisken_ismi"])

import numpy as np
m=np.arange(1,10).reshape((3,3))
m

df=pd.DataFrame(m,columns=["var1","var2","var3"])

df

df.axes

import numpy as np
s1=np.random.randint(10,size=5)
s2=np.random.randint(10,size=5)
s3=np.random.randint(10,size=5)

sozluk={"var1":s1,"var2":s2,"var3":s3}

sozluk





