# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T4oUN3xA1Mil0RtGM4UbZ21gL_2BypMP
"""

import numpy as np
import pandas as pd

m1=np.random.randint(3,30,size=(10,3))
df1=pd.DataFrame(m1,columns=["var1","var2","var3"])
df1

df2=df1+99
df2

"""dataframe deki bütün sayıları 99 ile topladı"""

df3=pd.concat([df1,df2],ignore_index=True)
df3

pd.concat([df1,df2],join='inner')

pd.concat([df1,df2],join_axes=[df1.columns],ignore_index=True)

"""İleri Birleştirme İşlemleri"""

df3=pd.DataFrame({'çalışanlar':["Ali","Veli","Ayşe","Fatma"],
                  'grup':["Muhasebe","Muhendislik","Muhendislik","IK"]})
df3

df4=pd.DataFrame({'çalışanlar':["Ali","Veli","Ayşe","Fatma"],
                 'ilk_giris':[2010,2009,2014,2020]})
df4

pd.merge(df3,df4)

df5=pd.merge(df3,df4,on='çalışanlar')

df6=pd.DataFrame({'grup':["Muhasebe","Muhendislik","IK"],
                 'mudur':["Caner","Aysel","Fatma"]})
df6

pd.merge(df5,df6)

